:memo: Add Release Schedule Information
moj-analytical-services/user-guidance pull request #461
Opened 2024-11-06 14:45 UTC by Gary-H9

This PR adds information relating to our Maintenance Policy for our newly defined IDE images.

2024-11-14 12:20 UTC, julialawrence requested changes
Just one nit.

2024-11-14 12:20 UTC, julialawrence commented on source/tools/ide-maintenance-policy/index.html.md.erb
> +<%= partial 'documentation/tools/ide-maintenance-policy/index' %>
```suggestion
<%= partial 'documentation/tools/ide-maintenance-policy/index' %>

```

2025-10-03 14:39 UTC, sdurnberger commented on source/documentation/tools/ide-maintenance-policy/index.md
> +In GitHub, we will include detailed release notes for each tool. You can find these here:
```suggestion
We will publish release notes of all changes for each tool. You can find these on GitHub:
```

2025-10-03 14:42 UTC, sdurnberger commented on source/documentation/tools/ide-maintenance-policy/index.md
> +
```suggestion

Release communications will summarise changes and provide a link to the relevant release note containing all changes.

```

2025-10-03 14:45 UTC, sdurnberger commented on source/documentation/tools/ide-maintenance-policy/index.md
> +
Would suggest this so users don't mistake a summary for being exhaustive. What do you think?

2025-10-03 14:45 UTC, sdurnberger commented on source/documentation/tools/ide-maintenance-policy/index.md
> +
```suggestion
```

2025-10-08 10:24 UTC, tamsinforbes approved these changes
🌝🌖🚀LGTM🚀🌘🌚

2025-10-08 14:56 UTC, merged