Update GITHUB_PAT guidance
moj-analytical-services/user-guidance pull request #93
Opened 2021-02-04 12:31 UTC by pjrh-moj

This update does two things:
1. adds a direct link to the Github PAT generating page, which pre-defines the scope to be only repo, and makes it easier to find.
2. changes the code provided to write the PAT to the .Renviron file instead of the .Rprofile file, which appears to be the recommended way.  The previous method of writing to the .Rprofile file doesn't work for me on the R upgrade to v4. (See also section "Where to put what?" in https://rviews.rstudio.com/2017/04/19/r-for-enterprise-understanding-r-s-startup/

2021-02-04 14:06 UTC, calumabarnett requested changes
Looks good – just a few small style tweaks

2021-02-04 14:06 UTC, calumabarnett commented on source/documentation/github.md
> +  1. Click [this link](https://github.com/settings/tokens/new?scopes=repo&description=R:GITHUB_PAT) to take you to right Github settings page. Or else you can navigate there on the Github site by goi
```suggestion
  1. Navigate to the [GitHub personal access tokens page](https://github.com/settings/tokens/new?scopes=repo&description=R:GITHUB_PAT). You can also access this from any other GitHub page by selecting your user icon, then **Settings**, then **Developer settings**, then **Personal access tokens**.
```

2021-02-04 14:06 UTC, calumabarnett commented on source/documentation/github.md
> +You should store your PAT in a special R file, called .Renviron, in your *home directory* (on AP). This file gets run when you start R, putting the PAT into the system environment variable `GITHUB_PA
```suggestion
You should store your PAT in a special R file, called `.Renviron` in your home directory on the Analytical Platform. This file gets run when you start R, putting the PAT into the system environment variable `GITHUB_PAT`. This is where common R packages (for example, remotes, devtools and renv) will look for it.
```

2021-02-04 14:41 UTC, pjrh-moj commented
Thanks @calumabarnett, that's much clearer.  I also had a re-read and realised that step 2 no longer made sense if you clicked the link so moved it to the second part of step 1 (I think you'll see what I mean in the commit).

Are you happy to now merge?

2021-02-04 14:58 UTC, calumabarnett approved these changes
All good 🚀

2021-02-05 11:45 UTC, merged

2021-02-09 08:16 UTC, pjrh-moj commented
@calumabarnett This PR hasn't managed to update the version of the guidance which is being hosted on https://user-guidance.services.alpha.mojanalytics.xyz/github.html#generating-a-pat - is there anything else we have to do to make this go live?

I notice in the readme it talks of automated deployment based on what is in the master branch, but the default branch now seems to be called main - is this causing the lack of deployment?

2021-02-09 09:08 UTC, calumabarnett commented
Thanks @pjrh-moj – I've created #94 to fix if you want to review